name: toggl_extractor
description: Tool to regularly extract data from Toggl
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.6.0
  http: ^1.3.0
  http_auth: ^1.0.4
  logging: ^1.3.0
  oxidized: ^6.2.0
  path: ^1.9.1
dev_dependencies:
  test: ^1.25.15
